# Generated by Django 4.1.6 on 2023-04-03 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.TextField(unique=True, verbose_name='Зав. № машины')),
                ('engine_serial_number', models.TextField(verbose_name='Зав. № двигателя')),
                ('transmission_serial_number', models.TextField(verbose_name='Зав. № трансмиссии')),
                ('driving_axle_serial_number', models.TextField(verbose_name='Зав. № ведущего моста')),
                ('steering_axle_serial_number', models.TextField(verbose_name='Зав. № управляемого моста')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.TextField(verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_adress', models.TextField(verbose_name='Адрес поставки (эксплуатации)')),
                ('additional_equipment', models.TextField(verbose_name='Комплектация (доп. опции)')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['shipment_date'],
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('manual_type', models.CharField(choices=[('Модель техники', 'Car Model'), ('Двигатель', 'Eninge Model'), ('Трансмиссия', 'Transmission Model'), ('Ведущий мост', 'Driving Axle Model'), ('Управляемый мост', 'Steering Axle Model'), ('Тип ТО', 'Maitenance Type'), ('Компания', 'Maitenance Provider'), ('Способ восстановления', 'Repair Method'), ('Узел отказа', 'Repair Unit')], max_length=50)),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сервисная организация',
                'verbose_name_plural': 'Сервисные организации',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.IntegerField(verbose_name='Наработка, м/час')),
                ('description', models.TextField(verbose_name='Описание отказа')),
                ('repair_parts', models.TextField(blank=True, null=True, verbose_name='Используемые запасные части')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата восстановления')),
                ('repair_time', models.IntegerField(blank=True, default=0, null=True, verbose_name='Время простоя техники')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car', verbose_name='Машина')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='repair_method', to='app.manual', verbose_name='Способ восстановления')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.servicecompany', verbose_name='Сервисная компания')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='repair_unit', to='app.manual', verbose_name='Узел отказа')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Maitenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.IntegerField(verbose_name='Наработка, м/час')),
                ('contract_serial_number', models.TextField(unique=True, verbose_name='№ заказ-наряда')),
                ('contract_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('self_maitenance', models.BooleanField(default=False, verbose_name='Самостоятельное проведение ТО')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car', verbose_name='Зав. № машины')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maitenance_provider', to='app.manual', verbose_name='Организация, проводившая ТО')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maitenance_service_company', to='app.servicecompany', verbose_name='Сервисная компания')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maitenance_type', to='app.manual', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'ТО',
                'verbose_name_plural': 'ТО',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='car',
            name='driving_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_driving_axle_model', to='app.manual', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_engine_model', to='app.manual', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_model', to='app.manual', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='car',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='car',
            name='steering_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_steering_axle_model', to='app.manual', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_transmission_model', to='app.manual', verbose_name='Модель трансмиссии'),
        ),
    ]
