# Generated by Django 4.1.6 on 2023-04-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_repair_service_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maitenance',
            name='provider',
        ),
    ]
